"""Applying cafecito to a project.

Three things stand between a fresh repo and a working plane, and every one of
them used to be the operator's homework: knowing the gate command, registering
the MCP server so agent sessions can find the plane, and keeping the tip
following commits made outside it. `cafecito init` does all three.

Detection is evidence-based and always explained — a plane whose gate collects
no tests lands everything unverified, so init says what it found and how it
knows, and warns loudly when it finds nothing.
"""

from __future__ import annotations

import json
import pathlib
import shlex
import stat

from .gitutil import git_rc

SKIP_DIRS = {".git", ".cafecito", "node_modules", "vendor", "dist", "build",
             "target", "__pycache__", ".venv", "venv", ".tox", ".next",
             ".pytest_cache", ".mypy_cache", "coverage", ".idea", ".vscode"}

MCP_FILE = ".mcp.json"
HOOK_MARKER = "cafecito advance"
# Both files, deliberately: CLAUDE.md is what Claude Code reads, AGENTS.md is the
# cross-tool convention. cafecito is protocol-neutral or it is nothing.
AGENTS_FILES = ("CLAUDE.md", "AGENTS.md")
AGENTS_BEGIN = "<!-- cafecito:begin"
AGENTS_END = "<!-- cafecito:end -->"
CI_FILE = ".github/workflows/cafecito.yml"
CI_MARKER = "Generated by `cafecito init --ci`"

# Toolchain setup per detected language. Versions float to latest so a fresh
# repo is green on generation; the header comment tells the operator to pin.
_CI_TOOLCHAIN = {
    "py": ["- uses: actions/setup-python@v5",
           "  with:",
           "    python-version: '3.x'   # pin to the version you support"],
    "js": ["- uses: actions/setup-node@v4",
           "  with:",
           "    node-version: 'lts/*'   # pin to the version you support"],
    "go": ["- uses: actions/setup-go@v5",
           "  with:",
           "    go-version: 'stable'"],
    "rust": ["- name: rust toolchain",
             "  run: rustup update stable && rustup default stable"],
}

# A post-commit hook is per-clone (.git/hooks is never committed), so init
# installs it. It must never fail a commit and never fire off the deploy
# branch: advance only follows commits the landed tip is an ancestor of.
HOOK_SCRIPT = """#!/bin/sh
# Installed by `cafecito init` — keeps the control plane's tip following
# commits made outside it, so the next landing bases on real history.
# Silent unless it advances; never fails a commit. CAFECITO_NO_HOOK=1 skips.
[ -n "$CAFECITO_NO_HOOK" ] && exit 0
command -v cafecito >/dev/null 2>&1 || exit 0
branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null) || exit 0
case "$branch" in
  main|master|trunk) ;;
  *) exit 0 ;;
esac
root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -d "$root/.cafecito" ] || exit 0
cafecito advance --repo "$root" --to HEAD >/dev/null 2>&1 || true
exit 0
"""

_TEST_SUFFIXES = {
    "py": ("test_", "_test.py"),
    "js": (".test.", ".spec."),
    "go": ("_test.go",),
}


def _read_json(path: pathlib.Path):
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def _walk(root: pathlib.Path, cap: int = 4000):
    """Repo files worth counting — skips the dependency and build noise that
    would otherwise drown a project's real test files."""
    seen = 0
    for path in root.rglob("*"):
        if seen >= cap:
            return
        if not path.is_file():
            continue
        if SKIP_DIRS & set(path.relative_to(root).parts):
            continue
        seen += 1
        yield path


def _count_tests(files: list[pathlib.Path]) -> dict[str, int]:
    counts = {"py": 0, "js": 0, "go": 0}
    for p in files:
        name = p.name
        if name.endswith(".py") and (name.startswith("test_")
                                     or name.endswith("_test.py")):
            counts["py"] += 1
        elif name.endswith((".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs")) \
                and (".test." in name or ".spec." in name):
            counts["js"] += 1
        elif name.endswith("_test.go"):
            counts["go"] += 1
    return counts


def _js_package(root: pathlib.Path, files: list[pathlib.Path]):
    """The package.json that owns the test script: root first, then one level
    down (the app-in-a-subdir layout is common)."""
    candidates = [root / "package.json"]
    candidates += sorted(p for p in files
                         if p.name == "package.json"
                         and len(p.relative_to(root).parts) == 2)
    for path in candidates:
        data = _read_json(path)
        if not isinstance(data, dict):
            continue
        script = (data.get("scripts") or {}).get("test", "")
        if script and "no test specified" not in script:
            return path, script
    return None, ""


def detect_project(repo: str) -> dict:
    """How this project tests itself, with the evidence for saying so.

    Returns test_cmd/setup_cmd/generated/gate_families plus `language`,
    `evidence`, and `test_files` (0 means the gate would have no signal —
    the caller must warn)."""
    root = pathlib.Path(repo).resolve()
    files = list(_walk(root))
    names = {str(p.relative_to(root)) for p in files}
    counts = _count_tests(files)
    found: list[dict] = []

    pkg_path, pkg_script = _js_package(root, files)
    if pkg_path is not None:
        prefix = pkg_path.parent.relative_to(root).as_posix()
        cmd = ["npm", "test", "--silent"]
        setup = ["npm", "ci"] if (pkg_path.parent / "package-lock.json").exists() \
            else ["npm", "install"]
        if prefix != ".":
            cmd += ["--prefix", prefix]
            setup += ["--prefix", prefix]
        lock = (f"{prefix}/package-lock.json" if prefix != "."
                else "package-lock.json")
        gen_cmd = ["npm", "install", "--package-lock-only"]
        if prefix != ".":
            gen_cmd += ["--prefix", prefix]
        found.append({
            "language": "js", "test_cmd": cmd, "setup_cmd": setup,
            "gate_families": ["js"],
            "generated": ({lock: gen_cmd}
                          if (pkg_path.parent / "package-lock.json").exists()
                          else {}),
            "test_files": counts["js"],
            "score": counts["js"] * 10 + 3,
            "evidence": [f"{pkg_path.relative_to(root)} scripts.test = "
                         f"{pkg_script!r}",
                         f"{counts['js']} test file(s)"],
        })

    py_manifest = next((n for n in ("pyproject.toml", "setup.py", "setup.cfg",
                                    "requirements.txt") if n in names), "")
    if py_manifest or counts["py"]:
        found.append({
            "language": "py",
            "test_cmd": ["python3", "-m", "pytest", "-q", "--tb=line",
                         "-p", "no:cacheprovider"],
            "setup_cmd": [], "gate_families": ["py"], "generated": {},
            "test_files": counts["py"],
            "score": counts["py"] * 10 + (2 if py_manifest else 0),
            "evidence": ([f"{py_manifest}"] if py_manifest else [])
            + [f"{counts['py']} test file(s)"],
        })

    if "go.mod" in names:
        found.append({
            "language": "go", "test_cmd": ["go", "test", "./..."],
            "setup_cmd": [], "gate_families": ["go"], "generated": {},
            "test_files": counts["go"],
            "score": counts["go"] * 10 + 2,
            "evidence": ["go.mod", f"{counts['go']} test file(s)"],
        })

    if "Cargo.toml" in names:
        found.append({
            "language": "rust", "test_cmd": ["cargo", "test"],
            "setup_cmd": [], "gate_families": [], "generated": {},
            "test_files": 0, "score": 1,
            "evidence": ["Cargo.toml",
                         "symbol analysis falls back to file granularity"],
        })

    if not found:
        return {"language": None, "test_cmd": None, "setup_cmd": [],
                "gate_families": [], "generated": {}, "test_files": 0,
                "evidence": ["no test runner detected"]}
    best = max(found, key=lambda c: c["score"])
    best["also_found"] = [c["language"] for c in found
                          if c["language"] != best["language"]]
    return best


def write_mcp_registration(repo: str, command: str = "cafecito") -> tuple[str, str]:
    """Register the plane in a checked-in .mcp.json so every session, clone,
    and worktree of this repo finds it — local-scope `claude mcp add` binds to
    one directory on one machine, which is how sessions end up silently
    committing around the plane. Merge-safe: other servers are preserved."""
    path = pathlib.Path(repo).resolve() / MCP_FILE
    entry = {"command": command, "args": ["serve", "--repo", "."]}
    if path.exists():
        data = _read_json(path)
        if not isinstance(data, dict):
            return "conflict", f"{MCP_FILE} exists but is not valid JSON"
        servers = data.setdefault("mcpServers", {})
        if not isinstance(servers, dict):
            return "conflict", f"{MCP_FILE} has a non-object mcpServers"
        if servers.get("cafecito") == entry:
            return "present", str(path)
        servers["cafecito"] = entry
        path.write_text(json.dumps(data, indent=2) + "\n")
        return "updated", str(path)
    path.write_text(json.dumps({"mcpServers": {"cafecito": entry}},
                               indent=2) + "\n")
    return "created", str(path)


def install_post_commit_hook(repo: str) -> tuple[str, str]:
    """Absorb bypass traffic: commits made without the plane (a maintainer on
    main, a GitHub web edit pulled down, another agent session with no MCP)
    move the tip instead of silently stranding it behind main."""
    code, out, _ = git_rc(repo, "rev-parse", "--git-path", "hooks")
    if code != 0:
        return "skipped", "no git hooks directory"
    hooks = pathlib.Path(repo).resolve() / out.strip()
    if not hooks.is_absolute():
        hooks = pathlib.Path(repo).resolve() / hooks
    hook = hooks / "post-commit"
    if hook.exists():
        existing = ""
        try:
            existing = hook.read_text()
        except OSError:
            pass
        if HOOK_MARKER in existing:
            return "present", str(hook)
        return "conflict", (f"{hook} exists — add this line to it: "
                            f"cafecito advance --repo \"$(git rev-parse "
                            f"--show-toplevel)\" --to HEAD >/dev/null 2>&1 || true")
    hooks.mkdir(parents=True, exist_ok=True)
    hook.write_text(HOOK_SCRIPT)
    hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return "installed", str(hook)


def mcp_registered(repo: str) -> bool:
    data = _read_json(pathlib.Path(repo).resolve() / MCP_FILE)
    return bool(isinstance(data, dict)
                and (data.get("mcpServers") or {}).get("cafecito"))


def hook_installed(repo: str) -> bool:
    code, out, _ = git_rc(repo, "rev-parse", "--git-path", "hooks")
    if code != 0:
        return False
    hook = pathlib.Path(repo).resolve() / out.strip() / "post-commit"
    try:
        return HOOK_MARKER in hook.read_text()
    except OSError:
        return False


def agent_instructions(config: dict) -> str:
    """What an agent needs to know to use the plane, in the file it already reads.

    No model has heard of cafecito — it postdates every training cutoff — so an
    agent session learns the plane exists from exactly two places: the MCP tool
    descriptions, and this stanza. The tools alone aren't enough: an agent that
    doesn't know it *should* land will happily `git commit` around the plane."""
    landed = config.get("branch", "cafecito/main")
    return f"""{AGENTS_BEGIN}: edit freely; delete this block to regenerate -->
## Landing changes (cafecito)

This repo coordinates parallel agent work through **cafecito**. Changes reach the deploy
branch by *landing* through the control plane — not by pushing.

- **Start from the plane's tip.** Call the `sync` tool (or `cafecito sync`) and work from
  the commit it returns, not from wherever the checkout happens to sit.
- **Reserve before editing.** Call `reserve` with the symbols or files you are about to
  change, so contention surfaces before the work is done instead of after it.
- **Land with `submit`.** Commit your work, then submit the sha. Changesets that touch
  different code land in parallel; real overlaps are regenerated automatically from both
  sides' intent; contradictions come back to a human. Every landing runs the test gate.
- **Don't push the deploy branch yourself.** The landed branch is `{landed}`, and `submit`
  is what moves it.
- **If the cafecito tools are not available in this session, say so and stop** rather than
  committing around the plane. A bypassed commit strands the tip, and the next landing
  builds on history the plane never saw.

Check state any time with `cafecito status`, or `cafecito doctor` for a health check.
{AGENTS_END}"""


def write_agent_instructions(repo: str, config: dict) -> tuple[str, str]:
    """Put the stanza where agents will actually see it. Appends to files that
    exist (never rewrites them), creates them when they don't. Marker-guarded, so
    a re-run is a no-op and operator edits inside the block survive."""
    root = pathlib.Path(repo).resolve()
    stanza = agent_instructions(config)
    created, appended, present = [], [], []
    for name in AGENTS_FILES:
        path = root / name
        if path.exists():
            try:
                body = path.read_text()
            except OSError:
                return "conflict", f"{name} exists but could not be read"
            if AGENTS_BEGIN in body:
                present.append(name)
                continue
            if body.endswith("\n\n"):
                sep = ""
            elif body.endswith("\n"):
                sep = "\n"
            else:
                sep = "\n\n"
            path.write_text(body + sep + stanza + "\n")
            appended.append(name)
        else:
            path.write_text(stanza + "\n")
            created.append(name)
    parts = []
    if created:
        parts.append(f"{' + '.join(created)} written")
    if appended:
        parts.append(f"stanza appended to {' + '.join(appended)}")
    if present:
        parts.append(f"already in {' + '.join(present)}")
    verdict = "present" if not created and not appended else "written"
    return verdict, "; ".join(parts)


def agent_instructions_present(repo: str) -> bool:
    root = pathlib.Path(repo).resolve()
    for name in AGENTS_FILES:
        try:
            if AGENTS_BEGIN in (root / name).read_text():
                return True
        except OSError:
            continue
    return False


def _ci_language(config: dict) -> str | None:
    """The language whose toolchain the workflow should set up. The plane's
    gate_families is the authority (it's what the gate itself keys on);
    test_cmd is the fallback when families are empty."""
    fams = config.get("gate_families") or []
    if fams and fams[0] in ("py", "js", "go"):
        return fams[0]
    cmd = config.get("test_cmd") or []
    base = pathlib.PurePosixPath(cmd[0]).name if cmd else ""
    if base.startswith("python") or "pytest" in cmd:
        return "py"
    if base in ("npm", "node", "npx", "yarn", "pnpm", "vitest", "jest"):
        return "js"
    if base == "go":
        return "go"
    if base == "cargo":
        return "rust"
    return None


def _ci_install_lines(lang: str | None, config: dict,
                      root: pathlib.Path) -> list[str]:
    """The install step's commands. A configured setup_cmd is authoritative —
    it's the same preparation the gate's worktrees get. Otherwise a
    language-appropriate best-effort, decided by what's actually on disk."""
    setup = config.get("setup_cmd") or []
    if setup:
        return [shlex.join(setup)]
    if lang == "py":
        lines = ["python -m pip install --upgrade pip"]
        if any((root / m).exists()
               for m in ("pyproject.toml", "setup.py", "setup.cfg")):
            lines.append("pip install -e .")
        elif (root / "requirements.txt").exists():
            lines.append("pip install -r requirements.txt")
        if "pytest" in (config.get("test_cmd") or []):
            lines.append("pip install pytest")
        return lines
    if lang == "go":
        return ["go mod download"]
    if lang == "js":
        return ["npm ci"]
    return []


def _render_ci(deploy: str, landed: str, toolchain: list[str],
               install: list[str], gate: str) -> str:
    L = ["# Generated by `cafecito init --ci`. Edit and commit freely.",
         "# Two jobs: your test gate, and a plane-sync guard that reddens when",
         f"# {landed} trails {deploy} — i.e. commits bypassed the landing gate.",
         "# Version pins float to latest; pin them to what you support.",
         "name: cafecito",
         "on:",
         "  push:",
         f"    branches: [{deploy}]",
         "  pull_request:",
         "",
         "jobs:",
         "  gate:",
         "    runs-on: ubuntu-latest",
         "    steps:",
         "      - uses: actions/checkout@v4"]
    L += ["      " + ln for ln in toolchain]
    if install:
        L += ["      - name: install", "        run: |"]
        L += ["          " + ln for ln in install]
    L += ["      - name: gate",
          f"        run: {gate}",
          "",
          "  # The plane must never trail the deploy branch: a direct commit",
          "  # bypasses the landing gate, and a stale landed branch means the",
          "  # next landing builds on history the plane never saw. Red here =",
          "  # someone forgot to advance the tip (`cafecito advance`).",
          "  plane-sync:",
          "    if: github.event_name == 'push'",
          "    runs-on: ubuntu-latest",
          "    steps:",
          "      - uses: actions/checkout@v4",
          "        with:",
          "          fetch-depth: 0",
          f"      - name: {landed} must be at or ahead of {deploy}",
          "        run: |",
          f"          if ! git fetch -q origin {landed} 2>/dev/null; then",
          f'            echo "no {landed} on origin yet — skipping"; exit 0',
          "          fi",
          '          if git merge-base --is-ancestor "$GITHUB_SHA" FETCH_HEAD; then',
          f'            echo "plane in sync: {landed} at or ahead of {deploy}"',
          "          else",
          f'            echo "::error::{landed} trails {deploy} — commits bypassed the plane."',
          f'            echo "catch up: cafecito advance --repo . && git push origin {deploy} {landed}"',
          "            exit 1",
          "          fi",
          ""]
    return "\n".join(L) + "\n"


def write_ci_workflow(repo: str, config: dict) -> tuple[str, str]:
    """Scaffold a GitHub Actions workflow: the project's own test gate plus a
    plane-sync guard that reddens when the landed branch trails the deploy
    branch — the CI-visible signal that commits bypassed the plane. Generated
    from the plane's own config, so the gate CI runs is the gate agents land
    on. Left untouched on re-run, so operator edits survive."""
    root = pathlib.Path(repo).resolve()
    path = root / CI_FILE
    if path.exists():
        try:
            body = path.read_text()
        except OSError:
            body = ""
        if CI_MARKER in body:
            return "present", str(path)
        return "conflict", f"{CI_FILE} exists and wasn't generated by cafecito"

    lang = _ci_language(config)
    landed = config.get("branch", "cafecito/main")
    code, out, _ = git_rc(repo, "symbolic-ref", "--quiet", "--short", "HEAD")
    deploy = out.strip() if code == 0 and out.strip() else "main"
    gate = shlex.join(config.get("test_cmd") or ["true"])

    text = _render_ci(deploy, landed, _CI_TOOLCHAIN.get(lang, []),
                      _ci_install_lines(lang, config, root), gate)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return "created", str(path)


def ci_workflow_present(repo: str) -> bool:
    try:
        return CI_MARKER in (pathlib.Path(repo).resolve()
                             / CI_FILE).read_text()
    except OSError:
        return False
